spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html
  profiles:
    active: dev     # 指定开发模式


comment.avatar: /images/avatar.jpg
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8
#    password: liuqiang0829
#    username: root
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.liuqiang.blog.pojo
#  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    root: info
#    com.liuqiang.blog: debug
#  file:
#    name: myblog.log


